server {
    listen 80;
    server_name localhost; # 또는 GCP VM의 외부 IP

    # Docker 내장 DNS
    resolver 127.0.0.11 valid=30s;

    # React 프론트엔드 전달
    location / {
        proxy_pass http://react-dev:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # FastAPI 백엔드 전달
    location /api/ {
        set $backend_upstream http://backend:8000;
        proxy_pass $backend_upstream;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}