"""create image generations table

Revision ID: 3717430aca14
Revises: 7e852317dc01
Create Date: 2026-09-09 15:08:25.754799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3717430aca14'
down_revision: Union[str, Sequence[str], None] = '7e852317dc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('original_image_url', sa.String(length=500), nullable=True),
    sa.Column('generated_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_generations_status'), 'image_generations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_generations_status'), table_name='image_generations')
    op.drop_table('image_generations')
    # ### end Alembic commands ###
