"""create v2 planning sessions and advertisement drafts

Revision ID: 523fbaf62992
Revises: 855b4583d0fc
Create Date: 2026-09-16 18:42:24.786167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523fbaf62992'
down_revision: Union[str, Sequence[str], None] = '855b4583d0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='planning', nullable=False),
    sa.Column('lodging_type', sa.String(length=30), nullable=True),
    sa.Column('lodging_type_detail', sa.String(length=50), nullable=True),
    sa.Column('lodging_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('selling_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('color_preference', sa.String(length=100), nullable=True),
    sa.Column('ad_copy', sa.String(length=60), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('original_image_url', sa.String(length=500), nullable=True),
    sa.Column('original_mime_type', sa.String(length=50), nullable=True),
    sa.Column('original_file_size', sa.BigInteger(), nullable=True),
    sa.Column('regeneration_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_sessions_status'), 'planning_sessions', ['status'], unique=False)
    op.create_table('advertisement_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('generation_round', sa.SmallInteger(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=50), server_default='image/png', nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['planning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'generation_round', 'direction', name='uq_advertisement_drafts_session_round_direction')
    )
    op.create_index(op.f('ix_advertisement_drafts_session_id'), 'advertisement_drafts', ['session_id'], unique=False)
    op.create_index(op.f('ix_advertisement_drafts_status'), 'advertisement_drafts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisement_drafts_status'), table_name='advertisement_drafts')
    op.drop_index(op.f('ix_advertisement_drafts_session_id'), table_name='advertisement_drafts')
    op.drop_table('advertisement_drafts')
    op.drop_index(op.f('ix_planning_sessions_status'), table_name='planning_sessions')
    op.drop_table('planning_sessions')
    # ### end Alembic commands ###
