"""replace prompt with advertisement fields

Revision ID: 855b4583d0fc
Revises: 3717430aca14
Create Date: 2026-09-10 17:32:40.528585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855b4583d0fc'
down_revision: Union[str, Sequence[str], None] = '3717430aca14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generations', sa.Column('hotel_description', sa.Text(), nullable=True))
    op.add_column('image_generations', sa.Column('ad_copy', sa.Text(), nullable=True))
    op.add_column('image_generations', sa.Column('additional_instructions', sa.Text(), nullable=True))
    # 기존 prompt는 추가 지시사항으로 보존
    op.execute(
        sa.text(
            """
            UPDATE image_generations
            SET hotel_description = '',
                ad_copy = '',
                additional_instructions = prompt
            """
        )
    )

    # 기존 데이터를 채운 후 필수 칼럼으로 변경
    op.alter_column(
        "image_generations",
        "hotel_description",
        existing_type=sa.Text(),
        nullable=False,
    )
    op.alter_column(
        "image_generations",
        "ad_copy",
        existing_type=sa.Text(),
        nullable=False,
    )

    # 마지막에 기존 prompt 칼럼 제거
    op.drop_column(
        "image_generations",
        "prompt",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generations', sa.Column('prompt', sa.TEXT(), nullable=True))
    # 보존해둔 추가 지시사항을 기존 prompt로 복원
    op.execute(
        sa.text(
            """
            UPDATE image_generations
            SET prompt = COALESCE(additional_instructions, '')
            """
        )
    )

    # 값을 채운 뒤 필수 칼럼으로 변경
    op.alter_column(
        "image_generations",
        "prompt",
        existing_type=sa.Text(),
        nullable=False,
    )
    op.drop_column('image_generations', 'additional_instructions')
    op.drop_column('image_generations', 'ad_copy')
    op.drop_column('image_generations', 'hotel_description')
    # ### end Alembic commands ###
