"""add lodging service to planning sessions

Revision ID: 92a0a09f65f8
Revises: 523fbaf62992
Create Date: 2026-09-29 17:48:55.105061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92a0a09f65f8'
down_revision: Union[str, Sequence[str], None] = '523fbaf62992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_sessions', sa.Column('lodging_service', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_sessions', 'lodging_service')
    # ### end Alembic commands ###
