# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc_stubs/hotel_advertisement_image.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/grpc_stubs/hotel_advertisement_image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.app/grpc_stubs/hotel_advertisement_image.proto\x12\x10hotel.adimage.v1\"\xb8\x01\n!GenerateAdvertisementImageRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x19\n\x11hotel_image_bytes\x18\x02 \x01(\x0c\x12\x17\n\x0fimage_mime_type\x18\x03 \x01(\t\x12\x19\n\x11hotel_description\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64_copy\x18\x05 \x01(\t\x12\x1f\n\x17\x61\x64\x64itional_instructions\x18\x06 \x01(\t\"R\n\"GenerateAdvertisementImageResponse\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x17\n\x0fimage_mime_type\x18\x02 \x01(\t\"\x14\n\x12HealthCheckRequest\"&\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x32\x86\x02\n\x1eHotelAdvertisementImageService\x12\x87\x01\n\x1aGenerateAdvertisementImage\x12\x33.hotel.adimage.v1.GenerateAdvertisementImageRequest\x1a\x34.hotel.adimage.v1.GenerateAdvertisementImageResponse\x12Z\n\x0bHealthCheck\x12$.hotel.adimage.v1.HealthCheckRequest\x1a%.hotel.adimage.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc_stubs.hotel_advertisement_image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEADVERTISEMENTIMAGEREQUEST']._serialized_start=69
  _globals['_GENERATEADVERTISEMENTIMAGEREQUEST']._serialized_end=253
  _globals['_GENERATEADVERTISEMENTIMAGERESPONSE']._serialized_start=255
  _globals['_GENERATEADVERTISEMENTIMAGERESPONSE']._serialized_end=337
  _globals['_HEALTHCHECKREQUEST']._serialized_start=339
  _globals['_HEALTHCHECKREQUEST']._serialized_end=359
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=361
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=399
  _globals['_HOTELADVERTISEMENTIMAGESERVICE']._serialized_start=402
  _globals['_HOTELADVERTISEMENTIMAGESERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
