# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_stubs import hotel_advertisement_image_pb2 as app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc_stubs/hotel_advertisement_image_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HotelAdvertisementImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAdvertisementImage = channel.unary_unary(
                '/hotel.adimage.v1.HotelAdvertisementImageService/GenerateAdvertisementImage',
                request_serializer=app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.GenerateAdvertisementImageRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.GenerateAdvertisementImageResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hotel.adimage.v1.HotelAdvertisementImageService/HealthCheck',
                request_serializer=app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HotelAdvertisementImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateAdvertisementImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelAdvertisementImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAdvertisementImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAdvertisementImage,
                    request_deserializer=app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.GenerateAdvertisementImageRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.GenerateAdvertisementImageResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.HealthCheckRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel.adimage.v1.HotelAdvertisementImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotel.adimage.v1.HotelAdvertisementImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotelAdvertisementImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateAdvertisementImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.adimage.v1.HotelAdvertisementImageService/GenerateAdvertisementImage',
            app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.GenerateAdvertisementImageRequest.SerializeToString,
            app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.GenerateAdvertisementImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.adimage.v1.HotelAdvertisementImageService/HealthCheck',
            app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.HealthCheckRequest.SerializeToString,
            app_dot_grpc__stubs_dot_hotel__advertisement__image__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
