# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_stubs import hotel_ad_v2_pb2 as app_dot_grpc__stubs_dot_hotel__ad__v2__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc_stubs/hotel_ad_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlanningAgentServiceStub(object):
    """V2 business contract. Independent of the vLLM engine protocol and V1.
    Both peers: max send/receive message size = 33,554,432 bytes (32 MiB).
    Application validation is required: proto3 itself does not enforce required
    fields, enum membership, bounds, state transitions, or image decoding rules.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTurn = channel.unary_unary(
                '/hotel.adimage.v2.PlanningAgentService/ProcessTurn',
                request_serializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.ProcessTurnRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.ProcessTurnResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hotel.adimage.v2.PlanningAgentService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PlanningAgentServiceServicer(object):
    """V2 business contract. Independent of the vLLM engine protocol and V1.
    Both peers: max send/receive message size = 33,554,432 bytes (32 MiB).
    Application validation is required: proto3 itself does not enforce required
    fields, enum membership, bounds, state transitions, or image decoding rules.
    """

    def ProcessTurn(self, request, context):
        """Unary. Initial deadline: 30 seconds. No server-side conversation state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlanningAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTurn,
                    request_deserializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.ProcessTurnRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.ProcessTurnResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel.adimage.v2.PlanningAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotel.adimage.v2.PlanningAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlanningAgentService(object):
    """V2 business contract. Independent of the vLLM engine protocol and V1.
    Both peers: max send/receive message size = 33,554,432 bytes (32 MiB).
    Application validation is required: proto3 itself does not enforce required
    fields, enum membership, bounds, state transitions, or image decoding rules.
    """

    @staticmethod
    def ProcessTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.adimage.v2.PlanningAgentService/ProcessTurn',
            app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.ProcessTurnRequest.SerializeToString,
            app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.ProcessTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.adimage.v2.PlanningAgentService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DraftImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateDraft = channel.unary_unary(
                '/hotel.adimage.v2.DraftImageService/GenerateDraft',
                request_serializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.GenerateDraftRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.GenerateDraftResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hotel.adimage.v2.DraftImageService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class DraftImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateDraft(self, request, context):
        """Unary, one draft per call. Initial deadline: 180 seconds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DraftImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDraft,
                    request_deserializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.GenerateDraftRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.GenerateDraftResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel.adimage.v2.DraftImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotel.adimage.v2.DraftImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DraftImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.adimage.v2.DraftImageService/GenerateDraft',
            app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.GenerateDraftRequest.SerializeToString,
            app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.GenerateDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.adimage.v2.DraftImageService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            app_dot_grpc__stubs_dot_hotel__ad__v2__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
