# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_stubs import vllm_engine_pb2 as app_dot_grpc__stubs_dot_vllm__engine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc_stubs/vllm_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VllmEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/vllm.grpc.engine.VllmEngine/Generate',
                request_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GenerateRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/vllm.grpc.engine.VllmEngine/Embed',
                request_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.EmbedRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/vllm.grpc.engine.VllmEngine/HealthCheck',
                request_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/vllm.grpc.engine.VllmEngine/Abort',
                request_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.AbortRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/vllm.grpc.engine.VllmEngine/GetModelInfo',
                request_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/vllm.grpc.engine.VllmEngine/GetServerInfo',
                request_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GetServerInfoResponse.FromString,
                _registered_method=True)


class VllmEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VllmEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GenerateRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GenerateResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.EmbedRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.EmbedResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.HealthCheckRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.AbortRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.AbortResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GetModelInfoRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GetServerInfoRequest.FromString,
                    response_serializer=app_dot_grpc__stubs_dot_vllm__engine__pb2.GetServerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vllm.grpc.engine.VllmEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vllm.grpc.engine.VllmEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VllmEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vllm.grpc.engine.VllmEngine/Generate',
            app_dot_grpc__stubs_dot_vllm__engine__pb2.GenerateRequest.SerializeToString,
            app_dot_grpc__stubs_dot_vllm__engine__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.grpc.engine.VllmEngine/Embed',
            app_dot_grpc__stubs_dot_vllm__engine__pb2.EmbedRequest.SerializeToString,
            app_dot_grpc__stubs_dot_vllm__engine__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.grpc.engine.VllmEngine/HealthCheck',
            app_dot_grpc__stubs_dot_vllm__engine__pb2.HealthCheckRequest.SerializeToString,
            app_dot_grpc__stubs_dot_vllm__engine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.grpc.engine.VllmEngine/Abort',
            app_dot_grpc__stubs_dot_vllm__engine__pb2.AbortRequest.SerializeToString,
            app_dot_grpc__stubs_dot_vllm__engine__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.grpc.engine.VllmEngine/GetModelInfo',
            app_dot_grpc__stubs_dot_vllm__engine__pb2.GetModelInfoRequest.SerializeToString,
            app_dot_grpc__stubs_dot_vllm__engine__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm.grpc.engine.VllmEngine/GetServerInfo',
            app_dot_grpc__stubs_dot_vllm__engine__pb2.GetServerInfoRequest.SerializeToString,
            app_dot_grpc__stubs_dot_vllm__engine__pb2.GetServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
